// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Open() {
  return window['go']['main']['LabDocument']['Open']();
}

export function Save(arg1) {
  return window['go']['main']['LabDocument']['Save'](arg1);
}

export function SaveAs(arg1) {
  return window['go']['main']['LabDocument']['SaveAs'](arg1);
}
