// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Open():Promise<void>;

export function Save(arg1:string):Promise<void>;

export function SaveAs(arg1:string):Promise<void>;
