// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CloseSerialPort(arg1:number):Promise<void>;

export function ListSerialPort():Promise<Array<string>>;

export function OpenSerialPort(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<number>;

export function SetContext(arg1:context.Context):Promise<void>;

export function WriteSerialPort(arg1:number,arg2:Array<number>):Promise<void>;
