// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListSerialPort():Promise<Array<string>>;

export function OpenSerialPort(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<void>;
