// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSerialPort(arg1) {
  return window['go']['main']['LabSerial']['CloseSerialPort'](arg1);
}

export function ListSerialPort() {
  return window['go']['main']['LabSerial']['ListSerialPort']();
}

export function OpenSerialPort(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['LabSerial']['OpenSerialPort'](arg1, arg2, arg3, arg4, arg5);
}

export function SetContext(arg1) {
  return window['go']['main']['LabSerial']['SetContext'](arg1);
}

export function WriteSerialPort(arg1, arg2) {
  return window['go']['main']['LabSerial']['WriteSerialPort'](arg1, arg2);
}
